dist: bionic

language: php

php:
  - 7.4

services:
  - mysql

install:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE homestead;'
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit
